name: Python
on: [push, workflow_dispatch, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install antlr4-python3-runtime==4.9.1
      - name: Run all the Python tests
        run: python3 tests/test_all.py
  pep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: 'Run PEP8 check'
        uses: quentinguidee/pep8-action@v1
        with:
          arguments: >-
            --exclude=.svn,CVS,.bzr,.hg,.git,zzantlr
            --ignore=E121,E123,E126,E133,E226,E241,E242,E704,W503,W504,W505,W191,E101,E128
